import type { Metadata } from "next";

import "./globals.css";

import { ColorSchemeScript, MantineProvider, mantineHtmlProps} from '@mantine/core';
import theme from "./theme";

export const metadata: Metadata = {
  title: "Ottoflow",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className="antialiased bg-[var(--mantine-color-dark-9)]">
        <MantineProvider theme={theme} defaultColorScheme="dark">
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
